insert into orders (id, store_id, customer_id) values (1, 10, 98);
insert into orders (id, store_id, customer_id) values (2, 4, 80);
insert into orders (id, store_id, customer_id) values (3, 21, 14);
insert into orders (id, store_id, customer_id) values (4, 22, 62);
insert into orders (id, store_id, customer_id) values (5, 15, 2);
insert into orders (id, store_id, customer_id) values (6, 19, 46);
insert into orders (id, store_id, customer_id) values (7, 21, 78);
insert into orders (id, store_id, customer_id) values (8, 24, 56);
insert into orders (id, store_id, customer_id) values (9, 25, 43);
insert into orders (id, store_id, customer_id) values (10, 10, 100);
insert into orders (id, store_id, customer_id) values (11, 6, 18);
insert into orders (id, store_id, customer_id) values (12, 3, 97);
insert into orders (id, store_id, customer_id) values (13, 18, 12);
insert into orders (id, store_id, customer_id) values (14, 18, 60);
insert into orders (id, store_id, customer_id) values (15, 3, 28);
insert into orders (id, store_id, customer_id) values (16, 2, 47);
insert into orders (id, store_id, customer_id) values (17, 6, 62);
insert into orders (id, store_id, customer_id) values (18, 16, 98);
insert into orders (id, store_id, customer_id) values (19, 6, 40);
insert into orders (id, store_id, customer_id) values (20, 23, 8);
insert into orders (id, store_id, customer_id) values (21, 23, 73);
insert into orders (id, store_id, customer_id) values (22, 6, 15);
insert into orders (id, store_id, customer_id) values (23, 12, 63);
insert into orders (id, store_id, customer_id) values (24, 19, 50);
insert into orders (id, store_id, customer_id) values (25, 6, 21);
insert into orders (id, store_id, customer_id) values (26, 14, 83);
insert into orders (id, store_id, customer_id) values (27, 18, 71);
insert into orders (id, store_id, customer_id) values (28, 14, 10);
insert into orders (id, store_id, customer_id) values (29, 5, 41);
insert into orders (id, store_id, customer_id) values (30, 14, 95);
insert into orders (id, store_id, customer_id) values (31, 12, 37);
insert into orders (id, store_id, customer_id) values (32, 15, 35);
insert into orders (id, store_id, customer_id) values (33, 13, 79);
insert into orders (id, store_id, customer_id) values (34, 4, 10);
insert into orders (id, store_id, customer_id) values (35, 8, 91);
insert into orders (id, store_id, customer_id) values (36, 3, 42);
insert into orders (id, store_id, customer_id) values (37, 25, 92);
insert into orders (id, store_id, customer_id) values (38, 16, 17);
insert into orders (id, store_id, customer_id) values (39, 13, 34);
insert into orders (id, store_id, customer_id) values (40, 9, 58);
insert into orders (id, store_id, customer_id) values (41, 19, 10);
insert into orders (id, store_id, customer_id) values (42, 13, 37);
insert into orders (id, store_id, customer_id) values (43, 14, 17);
insert into orders (id, store_id, customer_id) values (44, 2, 35);
insert into orders (id, store_id, customer_id) values (45, 22, 88);
insert into orders (id, store_id, customer_id) values (46, 4, 4);
insert into orders (id, store_id, customer_id) values (47, 24, 11);
insert into orders (id, store_id, customer_id) values (48, 6, 42);
insert into orders (id, store_id, customer_id) values (49, 20, 96);
insert into orders (id, store_id, customer_id) values (50, 25, 30);
insert into orders (id, store_id, customer_id) values (51, 7, 1);
insert into orders (id, store_id, customer_id) values (52, 7, 47);
insert into orders (id, store_id, customer_id) values (53, 15, 58);
insert into orders (id, store_id, customer_id) values (54, 8, 13);
insert into orders (id, store_id, customer_id) values (55, 23, 67);
insert into orders (id, store_id, customer_id) values (56, 5, 34);
insert into orders (id, store_id, customer_id) values (57, 14, 25);
insert into orders (id, store_id, customer_id) values (58, 6, 35);
insert into orders (id, store_id, customer_id) values (59, 24, 94);
insert into orders (id, store_id, customer_id) values (60, 5, 66);
insert into orders (id, store_id, customer_id) values (61, 23, 38);
insert into orders (id, store_id, customer_id) values (62, 16, 24);
insert into orders (id, store_id, customer_id) values (63, 16, 55);
insert into orders (id, store_id, customer_id) values (64, 14, 67);
insert into orders (id, store_id, customer_id) values (65, 2, 85);
insert into orders (id, store_id, customer_id) values (66, 21, 62);
insert into orders (id, store_id, customer_id) values (67, 21, 16);
insert into orders (id, store_id, customer_id) values (68, 20, 11);
insert into orders (id, store_id, customer_id) values (69, 3, 54);
insert into orders (id, store_id, customer_id) values (70, 20, 81);
insert into orders (id, store_id, customer_id) values (71, 2, 67);
insert into orders (id, store_id, customer_id) values (72, 17, 37);
insert into orders (id, store_id, customer_id) values (73, 23, 81);
insert into orders (id, store_id, customer_id) values (74, 23, 34);
insert into orders (id, store_id, customer_id) values (75, 8, 11);
insert into orders (id, store_id, customer_id) values (76, 5, 83);
insert into orders (id, store_id, customer_id) values (77, 17, 45);
insert into orders (id, store_id, customer_id) values (78, 16, 80);
insert into orders (id, store_id, customer_id) values (79, 7, 39);
insert into orders (id, store_id, customer_id) values (80, 7, 30);
insert into orders (id, store_id, customer_id) values (81, 24, 7);
insert into orders (id, store_id, customer_id) values (82, 19, 5);
insert into orders (id, store_id, customer_id) values (83, 13, 74);
insert into orders (id, store_id, customer_id) values (84, 15, 53);
insert into orders (id, store_id, customer_id) values (85, 12, 30);
insert into orders (id, store_id, customer_id) values (86, 3, 9);
insert into orders (id, store_id, customer_id) values (87, 23, 64);
insert into orders (id, store_id, customer_id) values (88, 3, 76);
insert into orders (id, store_id, customer_id) values (89, 19, 80);
insert into orders (id, store_id, customer_id) values (90, 6, 60);
insert into orders (id, store_id, customer_id) values (91, 4, 67);
insert into orders (id, store_id, customer_id) values (92, 22, 2);
insert into orders (id, store_id, customer_id) values (93, 15, 53);
insert into orders (id, store_id, customer_id) values (94, 2, 6);
insert into orders (id, store_id, customer_id) values (95, 14, 31);
insert into orders (id, store_id, customer_id) values (96, 23, 29);
insert into orders (id, store_id, customer_id) values (97, 12, 76);
insert into orders (id, store_id, customer_id) values (98, 18, 35);
insert into orders (id, store_id, customer_id) values (99, 15, 17);
insert into orders (id, store_id, customer_id) values (100, 11, 66);
insert into orders (id, store_id, customer_id) values (101, 9, 82);
insert into orders (id, store_id, customer_id) values (102, 17, 43);
insert into orders (id, store_id, customer_id) values (103, 20, 3);
insert into orders (id, store_id, customer_id) values (104, 4, 33);
insert into orders (id, store_id, customer_id) values (105, 2, 67);
insert into orders (id, store_id, customer_id) values (106, 3, 33);
insert into orders (id, store_id, customer_id) values (107, 2, 41);
insert into orders (id, store_id, customer_id) values (108, 20, 30);
insert into orders (id, store_id, customer_id) values (109, 14, 74);
insert into orders (id, store_id, customer_id) values (110, 20, 1);
insert into orders (id, store_id, customer_id) values (111, 3, 4);
insert into orders (id, store_id, customer_id) values (112, 14, 18);
insert into orders (id, store_id, customer_id) values (113, 10, 92);
insert into orders (id, store_id, customer_id) values (114, 22, 23);
insert into orders (id, store_id, customer_id) values (115, 12, 16);
insert into orders (id, store_id, customer_id) values (116, 9, 40);
insert into orders (id, store_id, customer_id) values (117, 9, 66);
insert into orders (id, store_id, customer_id) values (118, 24, 83);
insert into orders (id, store_id, customer_id) values (119, 22, 41);
insert into orders (id, store_id, customer_id) values (120, 11, 83);
insert into orders (id, store_id, customer_id) values (121, 12, 10);
insert into orders (id, store_id, customer_id) values (122, 23, 21);
insert into orders (id, store_id, customer_id) values (123, 22, 84);
insert into orders (id, store_id, customer_id) values (124, 19, 23);
insert into orders (id, store_id, customer_id) values (125, 12, 73);
insert into orders (id, store_id, customer_id) values (126, 22, 72);
insert into orders (id, store_id, customer_id) values (127, 2, 9);
insert into orders (id, store_id, customer_id) values (128, 20, 22);
insert into orders (id, store_id, customer_id) values (129, 23, 95);
insert into orders (id, store_id, customer_id) values (130, 13, 28);
insert into orders (id, store_id, customer_id) values (131, 7, 64);
insert into orders (id, store_id, customer_id) values (132, 22, 41);
insert into orders (id, store_id, customer_id) values (133, 9, 1);
insert into orders (id, store_id, customer_id) values (134, 21, 94);
insert into orders (id, store_id, customer_id) values (135, 8, 18);
insert into orders (id, store_id, customer_id) values (136, 19, 56);
insert into orders (id, store_id, customer_id) values (137, 9, 53);
insert into orders (id, store_id, customer_id) values (138, 14, 18);
insert into orders (id, store_id, customer_id) values (139, 14, 35);
insert into orders (id, store_id, customer_id) values (140, 10, 13);
insert into orders (id, store_id, customer_id) values (141, 20, 3);
insert into orders (id, store_id, customer_id) values (142, 20, 27);
insert into orders (id, store_id, customer_id) values (143, 12, 59);
insert into orders (id, store_id, customer_id) values (144, 7, 41);
insert into orders (id, store_id, customer_id) values (145, 24, 53);
insert into orders (id, store_id, customer_id) values (146, 4, 87);
insert into orders (id, store_id, customer_id) values (147, 11, 27);
insert into orders (id, store_id, customer_id) values (148, 16, 21);
insert into orders (id, store_id, customer_id) values (149, 7, 15);
insert into orders (id, store_id, customer_id) values (150, 18, 55);
insert into orders (id, store_id, customer_id) values (151, 21, 94);
insert into orders (id, store_id, customer_id) values (152, 13, 59);
insert into orders (id, store_id, customer_id) values (153, 24, 77);
insert into orders (id, store_id, customer_id) values (154, 10, 63);
insert into orders (id, store_id, customer_id) values (155, 14, 83);
insert into orders (id, store_id, customer_id) values (156, 19, 54);
insert into orders (id, store_id, customer_id) values (157, 13, 72);
insert into orders (id, store_id, customer_id) values (158, 14, 24);
insert into orders (id, store_id, customer_id) values (159, 25, 9);
insert into orders (id, store_id, customer_id) values (160, 5, 90);
insert into orders (id, store_id, customer_id) values (161, 8, 82);
insert into orders (id, store_id, customer_id) values (162, 13, 80);
insert into orders (id, store_id, customer_id) values (163, 4, 17);
insert into orders (id, store_id, customer_id) values (164, 21, 83);
insert into orders (id, store_id, customer_id) values (165, 9, 67);
insert into orders (id, store_id, customer_id) values (166, 15, 91);
insert into orders (id, store_id, customer_id) values (167, 20, 98);
insert into orders (id, store_id, customer_id) values (168, 11, 16);
insert into orders (id, store_id, customer_id) values (169, 12, 37);
insert into orders (id, store_id, customer_id) values (170, 13, 44);
insert into orders (id, store_id, customer_id) values (171, 25, 98);
insert into orders (id, store_id, customer_id) values (172, 17, 4);
insert into orders (id, store_id, customer_id) values (173, 15, 67);
insert into orders (id, store_id, customer_id) values (174, 13, 71);
insert into orders (id, store_id, customer_id) values (175, 5, 99);
insert into orders (id, store_id, customer_id) values (176, 25, 8);
insert into orders (id, store_id, customer_id) values (177, 14, 95);
insert into orders (id, store_id, customer_id) values (178, 16, 3);
insert into orders (id, store_id, customer_id) values (179, 14, 76);
insert into orders (id, store_id, customer_id) values (180, 22, 80);
insert into orders (id, store_id, customer_id) values (181, 5, 31);
insert into orders (id, store_id, customer_id) values (182, 9, 75);
insert into orders (id, store_id, customer_id) values (183, 9, 9);
insert into orders (id, store_id, customer_id) values (184, 20, 36);
insert into orders (id, store_id, customer_id) values (185, 25, 8);
insert into orders (id, store_id, customer_id) values (186, 21, 86);
insert into orders (id, store_id, customer_id) values (187, 16, 67);
insert into orders (id, store_id, customer_id) values (188, 4, 36);
insert into orders (id, store_id, customer_id) values (189, 7, 23);
insert into orders (id, store_id, customer_id) values (190, 23, 38);
insert into orders (id, store_id, customer_id) values (191, 17, 1);
insert into orders (id, store_id, customer_id) values (192, 11, 81);
insert into orders (id, store_id, customer_id) values (193, 18, 100);
insert into orders (id, store_id, customer_id) values (194, 21, 4);
insert into orders (id, store_id, customer_id) values (195, 5, 78);
insert into orders (id, store_id, customer_id) values (196, 21, 36);
insert into orders (id, store_id, customer_id) values (197, 19, 87);
insert into orders (id, store_id, customer_id) values (198, 8, 40);
insert into orders (id, store_id, customer_id) values (199, 4, 66);
insert into orders (id, store_id, customer_id) values (200, 19, 2);
insert into orders (id, store_id, customer_id) values (201, 1, 46);
insert into orders (id, store_id, customer_id) values (202, 1, 56);
insert into orders (id, store_id, customer_id) values (203, 1, 99);
insert into orders (id, store_id, customer_id) values (204, 1, 11);
insert into orders (id, store_id, customer_id) values (205, 1, 35);
insert into orders (id, store_id, customer_id) values (206, 1, 24);
insert into orders (id, store_id, customer_id) values (207, 1, 12);
insert into orders (id, store_id, customer_id) values (208, 1, 90);
insert into orders (id, store_id, customer_id) values (209, 1, 71);
insert into orders (id, store_id, customer_id) values (210, 1, 69);
insert into orders (id, store_id, customer_id) values (211, 1, 32);
insert into orders (id, store_id, customer_id) values (212, 1, 99);
insert into orders (id, store_id, customer_id) values (213, 1, 63);
insert into orders (id, store_id, customer_id) values (214, 1, 38);
insert into orders (id, store_id, customer_id) values (215, 1, 44);
insert into orders (id, store_id, customer_id) values (216, 1, 100);
insert into orders (id, store_id, customer_id) values (217, 1, 83);
insert into orders (id, store_id, customer_id) values (218, 1, 15);
insert into orders (id, store_id, customer_id) values (219, 1, 74);
insert into orders (id, store_id, customer_id) values (220, 1, 22);
insert into orders (id, store_id, customer_id) values (221, 1, 93);
insert into orders (id, store_id, customer_id) values (222, 1, 13);
insert into orders (id, store_id, customer_id) values (223, 1, 69);
insert into orders (id, store_id, customer_id) values (224, 1, 74);
insert into orders (id, store_id, customer_id) values (225, 1, 71);
insert into orders (id, store_id, customer_id) values (226, 1, 20);
insert into orders (id, store_id, customer_id) values (227, 1, 11);
insert into orders (id, store_id, customer_id) values (228, 1, 21);
insert into orders (id, store_id, customer_id) values (229, 1, 100);
insert into orders (id, store_id, customer_id) values (230, 1, 14);
insert into orders (id, store_id, customer_id) values (231, 1, 91);
insert into orders (id, store_id, customer_id) values (232, 1, 9);
insert into orders (id, store_id, customer_id) values (233, 1, 69);
insert into orders (id, store_id, customer_id) values (234, 1, 11);
insert into orders (id, store_id, customer_id) values (235, 1, 76);
insert into orders (id, store_id, customer_id) values (236, 1, 51);
insert into orders (id, store_id, customer_id) values (237, 1, 55);
insert into orders (id, store_id, customer_id) values (238, 1, 34);
insert into orders (id, store_id, customer_id) values (239, 1, 31);
insert into orders (id, store_id, customer_id) values (240, 1, 56);
insert into orders (id, store_id, customer_id) values (241, 1, 22);
insert into orders (id, store_id, customer_id) values (242, 1, 46);
insert into orders (id, store_id, customer_id) values (243, 1, 4);
insert into orders (id, store_id, customer_id) values (244, 1, 73);
insert into orders (id, store_id, customer_id) values (245, 1, 20);
insert into orders (id, store_id, customer_id) values (246, 1, 78);
insert into orders (id, store_id, customer_id) values (247, 1, 37);
insert into orders (id, store_id, customer_id) values (248, 1, 8);
insert into orders (id, store_id, customer_id) values (249, 1, 1);
insert into orders (id, store_id, customer_id) values (250, 1, 41);
insert into orders (id, store_id, customer_id) values (251, 1, 20);
insert into orders (id, store_id, customer_id) values (252, 1, 79);
insert into orders (id, store_id, customer_id) values (253, 1, 98);
insert into orders (id, store_id, customer_id) values (254, 1, 31);
insert into orders (id, store_id, customer_id) values (255, 1, 95);
insert into orders (id, store_id, customer_id) values (256, 1, 67);
insert into orders (id, store_id, customer_id) values (257, 1, 37);
insert into orders (id, store_id, customer_id) values (258, 1, 17);
insert into orders (id, store_id, customer_id) values (259, 1, 73);
insert into orders (id, store_id, customer_id) values (260, 1, 4);
insert into orders (id, store_id, customer_id) values (261, 1, 56);
insert into orders (id, store_id, customer_id) values (262, 1, 58);
insert into orders (id, store_id, customer_id) values (263, 1, 92);
insert into orders (id, store_id, customer_id) values (264, 1, 39);
insert into orders (id, store_id, customer_id) values (265, 1, 43);
insert into orders (id, store_id, customer_id) values (266, 1, 21);
insert into orders (id, store_id, customer_id) values (267, 1, 94);
insert into orders (id, store_id, customer_id) values (268, 1, 51);
insert into orders (id, store_id, customer_id) values (269, 1, 48);
insert into orders (id, store_id, customer_id) values (270, 1, 68);
insert into orders (id, store_id, customer_id) values (271, 1, 70);
insert into orders (id, store_id, customer_id) values (272, 1, 38);
insert into orders (id, store_id, customer_id) values (273, 1, 82);
insert into orders (id, store_id, customer_id) values (274, 1, 100);
insert into orders (id, store_id, customer_id) values (275, 1, 16);
insert into orders (id, store_id, customer_id) values (276, 1, 80);
insert into orders (id, store_id, customer_id) values (277, 1, 46);
insert into orders (id, store_id, customer_id) values (278, 1, 42);
insert into orders (id, store_id, customer_id) values (279, 1, 35);
insert into orders (id, store_id, customer_id) values (280, 1, 17);
insert into orders (id, store_id, customer_id) values (281, 1, 40);
insert into orders (id, store_id, customer_id) values (282, 1, 26);
insert into orders (id, store_id, customer_id) values (283, 1, 62);
insert into orders (id, store_id, customer_id) values (284, 1, 81);
insert into orders (id, store_id, customer_id) values (285, 1, 20);
insert into orders (id, store_id, customer_id) values (286, 1, 83);
insert into orders (id, store_id, customer_id) values (287, 1, 99);
insert into orders (id, store_id, customer_id) values (288, 1, 62);
insert into orders (id, store_id, customer_id) values (289, 1, 99);
insert into orders (id, store_id, customer_id) values (290, 1, 32);
insert into orders (id, store_id, customer_id) values (291, 1, 45);
insert into orders (id, store_id, customer_id) values (292, 1, 85);
insert into orders (id, store_id, customer_id) values (293, 1, 53);
insert into orders (id, store_id, customer_id) values (294, 1, 85);
insert into orders (id, store_id, customer_id) values (295, 1, 45);
insert into orders (id, store_id, customer_id) values (296, 1, 61);
insert into orders (id, store_id, customer_id) values (297, 1, 8);
insert into orders (id, store_id, customer_id) values (298, 1, 5);
insert into orders (id, store_id, customer_id) values (299, 1, 2);
insert into orders (id, store_id, customer_id) values (300, 1, 39);
insert into orders (id, store_id) values (301, 7);
insert into orders (id, store_id) values (302, 19);
insert into orders (id, store_id) values (303, 13);
insert into orders (id, store_id) values (304, 8);
insert into orders (id, store_id) values (305, 13);
insert into orders (id, store_id) values (306, 18);
insert into orders (id, store_id) values (307, 10);
insert into orders (id, store_id) values (308, 10);
insert into orders (id, store_id) values (309, 5);
insert into orders (id, store_id) values (310, 15);
insert into orders (id, store_id) values (311, 16);
insert into orders (id, store_id) values (312, 5);
insert into orders (id, store_id) values (313, 8);
insert into orders (id, store_id) values (314, 9);
insert into orders (id, store_id) values (315, 25);
insert into orders (id, store_id) values (316, 18);
insert into orders (id, store_id) values (317, 5);
insert into orders (id, store_id) values (318, 13);
insert into orders (id, store_id) values (319, 14);
insert into orders (id, store_id) values (320, 16);
insert into orders (id, store_id) values (321, 3);
insert into orders (id, store_id) values (322, 7);
insert into orders (id, store_id) values (323, 12);
insert into orders (id, store_id) values (324, 6);
insert into orders (id, store_id) values (325, 3);
insert into orders (id, store_id) values (326, 22);
insert into orders (id, store_id) values (327, 14);
insert into orders (id, store_id) values (328, 15);
insert into orders (id, store_id) values (329, 14);
insert into orders (id, store_id) values (330, 19);
insert into orders (id, store_id) values (331, 11);
insert into orders (id, store_id) values (332, 10);
insert into orders (id, store_id) values (333, 4);
insert into orders (id, store_id) values (334, 13);
insert into orders (id, store_id) values (335, 5);
insert into orders (id, store_id) values (336, 14);
insert into orders (id, store_id) values (337, 18);
insert into orders (id, store_id) values (338, 20);
insert into orders (id, store_id) values (339, 3);
insert into orders (id, store_id) values (340, 2);
insert into orders (id, store_id) values (341, 2);
insert into orders (id, store_id) values (342, 8);
insert into orders (id, store_id) values (343, 13);
insert into orders (id, store_id) values (344, 15);
insert into orders (id, store_id) values (345, 13);
insert into orders (id, store_id) values (346, 4);
insert into orders (id, store_id) values (347, 13);
insert into orders (id, store_id) values (348, 15);
insert into orders (id, store_id) values (349, 18);
insert into orders (id, store_id) values (350, 22);