insert into brands (id, name, web_site, vendor_id) values (1, 'Nestlé', 'omckeady0@nydailynews.com', 1);
insert into brands (id, name, web_site, vendor_id) values (2, 'PepsiCo', 'icarrett1@sfgate.com', 2);
insert into brands (id, name, web_site, vendor_id) values (3, 'Inc.', 'elopes2@google.es', 3);
insert into brands (id, name, web_site, vendor_id) values (4, 'Tyson Foods', 'cwhitsey3@aboutads.info', 4);
insert into brands (id, name, web_site, vendor_id) values (5, 'The Coca-Cola Company', 'gdarnody4@redcross.org', 5);
insert into brands (id, name, web_site, vendor_id) values (6, 'Danone', 'rclemenson5@discovery.com', 6);
insert into brands (id, name, web_site, vendor_id) values (7, 'Unilever', 'lmatteotti6@jiathis.com', 7);
insert into brands (id, name, web_site, vendor_id) values (8, 'Yamazaki Baking', 'amaymond7@state.tx.us', 8);
insert into brands (id, name, web_site, vendor_id) values (9, 'The Hershey Company', 'ckleisel8@guardian.co.uk', 9);
insert into brands (id, name, web_site, vendor_id) values (10, 'Pampers', 'oarthey9@alexa.com', 10);
insert into brands (id, name, web_site, vendor_id) values (11, 'Dove', 'mbrooktona@timesonline.co.uk', 11);
insert into brands (id, name, web_site, vendor_id) values (12, 'Colgate', 'lfenneb@wired.com', 12);
insert into brands (id, name, web_site, vendor_id) values (13, 'Aveeno', 'uhaylesc@booking.com', 13);
insert into brands (id, name, web_site, vendor_id) values (14, 'Splat', 'lkonmannd@pinterest.com', 14);
insert into brands (id, name, web_site, vendor_id) values (15, 'Elseve', 'nivanyushine@sogou.com', 15);
insert into brands (id, name, web_site, vendor_id) values (16, 'Domestos', 'cmaggioref@slashdot.org', 1);
insert into brands (id, name, web_site, vendor_id) values (17, 'Comet', 'awroeg@cafepress.com', 1);
insert into brands (id, name, web_site, vendor_id) values (18, 'Adal', 'wbeazeh@gnu.org', 2);
insert into brands (id, name, web_site, vendor_id) values (19, 'Bakery Goods', 'dslocombi@4shared.com', 3);
insert into brands (id, name, web_site, vendor_id) values (20, 'Fresh Meat', 'dbeadonj@g.co', 4);
insert into brands (id, name, web_site, vendor_id) values (21, 'Sea Food', 'sendriccik@topsy.com', 5);
insert into brands (id, name, web_site, vendor_id) values (22, 'Greens', 'btaffarellol@i2i.jp', 6);
