insert into category (id, name, super_category) values (1, 'Pastry', 'Frozen_Food');
insert into category (id, name, super_category) values (2, 'Meals', 'Frozen_Food');
insert into category (id, name, super_category) values (3, 'Juice', 'Beverages');
insert into category (id, name, super_category) values (4, 'Soda', 'Beverages');
insert into category (id, name, super_category) values (5, 'Water', 'Beverages');
insert into category (id, name, super_category) values (6, 'Milk', 'Dairy_Eggs');
insert into category (id, name, super_category) values (7, 'Yoghurt', 'Dairy_Eggs');
insert into category (id, name, super_category) values (8, 'Fish', 'Meat');
insert into category (id, name, super_category) values (9, 'Chocolate', 'Snacks');
insert into category (id, name, super_category) values (10, 'Sweets', 'Snacks');
insert into category (id, name, super_category) values (11, 'Cookies', 'Snacks');
insert into category (id, name, super_category) values (12, 'Beef', 'Meat');
insert into category (id, name, super_category) values (13, 'Chicken', 'Meat');
insert into category (id, name, super_category) values (14, 'Lamb', 'Meat');
insert into category (id, name, super_category) values (15, 'Fruits', 'Fresh');
insert into category (id, name, super_category) values (16, 'Vegetables', 'Fresh');
insert into category (id, name, super_category) values (17, 'Bread', 'Baked');
insert into category (id, name, super_category) values (18, 'Pie', 'Baked');
insert into category (id, name, super_category) values (19, 'Cleaners', 'Chemicals');
insert into category (id, name, super_category) values (20, 'Creams', 'Personal Care');
insert into category (id, name, super_category) values (21, 'Dental', 'Personal Care');
insert into category (id, name, super_category) values (22, 'Hair_Products', 'Personal Care');
insert into category (id, name, super_category) values (23, 'Utilities', 'Chemicals');
insert into category (id, name, super_category) values (24, 'Eggs', 'Dairy_Eggs');
