insert into customers (id, name, address, city, phone_number, e_mail) values (1, 'Trula Cryer', '18001 Raven Lane', 'Taraz', '329-704-8774', 'tcryer0@yellowbook.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (2, 'Trevar Parfitt', '15749 Magdeline Terrace', 'Aktobe', '530-850-0737', 'tparfitt1@parallels.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (3, 'Nonie Gudde', '2310 Fairfield Place', 'Shymkent', '492-404-3190', 'ngudde2@apple.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (4, 'Jenica Rusling', '8 Mosinee Pass', 'Atyrau', '352-936-8327', 'jrusling3@nytimes.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (5, 'Swen Winspurr', '01 Utah Circle', 'Semei', '266-422-7191', 'swinspurr4@tripadvisor.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (6, 'Mortimer Burberye', '68969 Vahlen Hill', 'Ust-Kamenogorsk', '234-253-5224', 'mburberye5@arstechnica.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (7, 'Symon Morrissey', '5 Transport Lane', 'Shymkent', '478-440-8787', 'smorrissey6@ask.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (8, 'Enrica Underhill', '9 Sloan Lane', 'Nur-Sultan', '239-499-7007', 'eunderhill7@ehow.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (9, 'Dennet Wallhead', '468 Drewry Parkway', 'Aktau', '834-480-4818', 'dwallhead8@hp.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (10, 'Wyatt Faithorn', '8 Sunnyside Way', 'Taraz', '515-180-8878', 'wfaithorn9@wikispaces.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (11, 'Morgana Poupard', '3 Donald Road', 'Kokshetau', '848-800-4415', 'mpouparda@loc.gov');
insert into customers (id, name, address, city, phone_number, e_mail) values (12, 'Desirae Wyles', '7583 Buena Vista Place', 'Semei', '321-640-9620', 'dwylesb@hugedomains.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (13, 'Dell Bennetto', '70 Mendota Court', 'Nur-Sultan', '832-109-7121', 'dbennettoc@mac.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (14, 'Antone Chomley', '4141 Grayhawk Parkway', 'Nur-Sultan', '115-554-3002', 'achomleyd@nps.gov');
insert into customers (id, name, address, city, phone_number, e_mail) values (15, 'Weider Hazley', '29709 Roth Place', 'Pavlodar', '772-193-5923', 'whazleye@nasa.gov');
insert into customers (id, name, address, city, phone_number, e_mail) values (16, 'Tiphani Ghiron', '2 Spohn Parkway', 'Ust-Kamenogorsk', '754-688-3554', 'tghironf@buzzfeed.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (17, 'Violette Teideman', '3169 Holy Cross Drive', 'Ust-Kamenogorsk', '598-502-4163', 'vteidemang@google.cn');
insert into customers (id, name, address, city, phone_number, e_mail) values (18, 'Gavra Vanini', '72 Warrior Drive', 'Pavlodar', '882-377-1885', 'gvaninih@amazon.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (19, 'Magdalena Pavlov', '07376 Spenser Point', 'Almaty', '171-693-8080', 'mpavlovi@nsw.gov.au');
insert into customers (id, name, address, city, phone_number, e_mail) values (20, 'Mavis Gosforth', '550 Spaight Plaza', 'Shymkent', '945-754-1189', 'mgosforthj@usda.gov');
insert into customers (id, name, address, city, phone_number, e_mail) values (21, 'Jacqui Tante', '705 Delaware Alley', 'Aktobe', '783-213-6743', 'jtantek@hud.gov');
insert into customers (id, name, address, city, phone_number, e_mail) values (22, 'Rufus Kettle', '28308 Golf View Way', 'Kokshetau', '493-140-4990', 'rkettlel@delicious.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (23, 'Magda Wintle', '2882 Lillian Drive', 'Ust-Kamenogorsk', '503-535-2092', 'mwintlem@reference.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (24, 'Ninon Kilcullen', '723 Fordem Circle', 'Aktobe', '243-781-1550', 'nkilcullenn@multiply.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (25, 'Cathleen Beckerleg', '081 Orin Drive', 'Kokshetau', '545-468-2642', 'cbeckerlego@washingtonpost.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (26, 'Allister Wormell', '299 Roth Parkway', 'Pavlodar', '183-473-4709', 'awormellp@unicef.org');
insert into customers (id, name, address, city, phone_number, e_mail) values (27, 'Franz Strauss', '830 Center Court', 'Almaty', '722-656-7314', 'fstraussq@mozilla.org');
insert into customers (id, name, address, city, phone_number, e_mail) values (28, 'Abbott Noble', '26 Canary Crossing', 'Nur-Sultan', '115-161-4264', 'anobler@google.de');
insert into customers (id, name, address, city, phone_number, e_mail) values (29, 'Roberta Heinzler', '7432 Spenser Crossing', 'Shymkent', '956-101-8056', 'rheinzlers@youku.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (30, 'Lindsay Thomassen', '71 Esker Terrace', 'Semei', '319-424-1087', 'lthomassent@homestead.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (31, 'Nelie McKean', '71 Reindahl Way', 'Semei', '612-769-9839', 'nmckeanu@amazon.co.jp');
insert into customers (id, name, address, city, phone_number, e_mail) values (32, 'Allyce Wardall', '4220 Sloan Terrace', 'Atyrau', '529-582-4584', 'awardallv@opensource.org');
insert into customers (id, name, address, city, phone_number, e_mail) values (33, 'Lilith Crichten', '0 Elgar Way', 'Aktobe', '649-753-9748', 'lcrichtenw@icq.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (34, 'Adan Raspel', '458 Northridge Alley', 'Kokshetau', '825-961-4662', 'araspelx@harvard.edu');
insert into customers (id, name, address, city, phone_number, e_mail) values (35, 'Stace De La Salle', '782 Bartelt Alley', 'Nur-Sultan', '704-959-5910', 'sdey@miitbeian.gov.cn');
insert into customers (id, name, address, city, phone_number, e_mail) values (36, 'Gertrudis Tuohy', '7472 Ilene Terrace', 'Nur-Sultan', '700-738-6021', 'gtuohyz@shinystat.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (37, 'Maxie Upwood', '66094 Barby Parkway', 'Almaty', '303-545-5192', 'mupwood10@w3.org');
insert into customers (id, name, address, city, phone_number, e_mail) values (38, 'Merralee Goodlake', '38629 3rd Street', 'Nur-Sultan', '673-826-0262', 'mgoodlake11@webeden.co.uk');
insert into customers (id, name, address, city, phone_number, e_mail) values (39, 'Jennee Donne', '04384 Manufacturers Street', 'Semei', '855-482-4062', 'jdonne12@nasa.gov');
insert into customers (id, name, address, city, phone_number, e_mail) values (40, 'Wenona Paternoster', '0300 Buhler Lane', 'Semei', '851-903-2618', 'wpaternoster13@discovery.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (41, 'Erena Gairdner', '3 Ludington Parkway', 'Kyzylorda', '794-526-1004', 'egairdner14@biblegateway.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (42, 'Dare Lownds', '23 Dayton Lane', 'Aktobe', '648-965-1244', 'dlownds15@mysql.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (43, 'Cristen Garvan', '4 Upham Crossing', 'Kokshetau', '244-591-3236', 'cgarvan16@theglobeandmail.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (44, 'Rachele Filyashin', '79 Hermina Court', 'Atyrau', '626-828-5618', 'rfilyashin17@tinypic.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (45, 'Georg Sycamore', '53469 Katie Street', 'Shymkent', '865-774-8838', 'gsycamore18@goo.gl');
insert into customers (id, name, address, city, phone_number, e_mail) values (46, 'Clayborne Raffeorty', '711 Truax Court', 'Atyrau', '369-910-7367', 'craffeorty19@myspace.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (47, 'Garald Pridgeon', '10 Meadow Ridge Pass', 'Atyrau', '689-566-8689', 'gpridgeon1a@senate.gov');
insert into customers (id, name, address, city, phone_number, e_mail) values (48, 'Geordie Mattielli', '4730 Upham Park', 'Nur-Sultan', '610-974-9230', 'gmattielli1b@furl.net');
insert into customers (id, name, address, city, phone_number, e_mail) values (49, 'Torrey Cadore', '7426 Dunning Place', 'Almaty', '586-951-9309', 'tcadore1c@addtoany.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (50, 'Gusti Odlin', '39 Columbus Street', 'Aktau', '450-603-0062', 'godlin1d@1688.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (51, 'Gretna O''Kinedy', '4483 Steensland Place', 'Almaty', '564-820-8524', 'gokinedy1e@photobucket.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (52, 'Merwyn Wychard', '29 Ruskin Trail', 'Semei', '599-774-9542', 'mwychard1f@youku.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (53, 'Constantino Huntly', '4 Larry Lane', 'Ust-Kamenogorsk', '236-989-5543', 'chuntly1g@dion.ne.jp');
insert into customers (id, name, address, city, phone_number, e_mail) values (54, 'Lucie Elderbrant', '617 Acker Court', 'Aktau', '372-735-5841', 'lelderbrant1h@harvard.edu');
insert into customers (id, name, address, city, phone_number, e_mail) values (55, 'Iolanthe Cussins', '83 Nova Park', 'Nur-Sultan', '195-320-9446', 'icussins1i@toplist.cz');
insert into customers (id, name, address, city, phone_number, e_mail) values (56, 'Estelle Gilbard', '42 Shoshone Pass', 'Semei', '665-694-5328', 'egilbard1j@sciencedaily.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (57, 'Korrie Langabeer', '016 Bluestem Crossing', 'Almaty', '427-877-8196', 'klangabeer1k@123-reg.co.uk');
insert into customers (id, name, address, city, phone_number, e_mail) values (58, 'Randell Piniur', '0 Macpherson Point', 'Semei', '142-925-9187', 'rpiniur1l@examiner.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (59, 'Bab Kinchlea', '83854 Old Gate Crossing', 'Semei', '999-176-9900', 'bkinchlea1m@ftc.gov');
insert into customers (id, name, address, city, phone_number, e_mail) values (60, 'Madella Heathwood', '79 Havey Way', 'Almaty', '903-721-0465', 'mheathwood1n@about.me');
insert into customers (id, name, address, city, phone_number, e_mail) values (61, 'Antone Bridie', '6 Hintze Place', 'Almaty', '381-977-8438', 'abridie1o@jalbum.net');
insert into customers (id, name, address, city, phone_number, e_mail) values (62, 'Torin Duligall', '72493 Clarendon Avenue', 'Aktau', '727-495-9257', 'tduligall1p@sitemeter.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (63, 'Tobit Maughan', '415 Little Fleur Circle', 'Pavlodar', '352-187-0875', 'tmaughan1q@accuweather.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (64, 'Kay Trebble', '588 Talmadge Center', 'Atyrau', '659-237-2131', 'ktrebble1r@google.com.au');
insert into customers (id, name, address, city, phone_number, e_mail) values (65, 'Elysha Illyes', '6 Buena Vista Court', 'Semei', '284-217-3439', 'eillyes1s@rediff.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (66, 'Gisele Myles', '5 Evergreen Drive', 'Semei', '510-627-5342', 'gmyles1t@vistaprint.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (67, 'Filia Philipard', '77 Toban Street', 'Kyzylorda', '526-730-9365', 'fphilipard1u@wsj.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (68, 'Kata Crayk', '08102 International Park', 'Taraz', '825-591-9880', 'kcrayk1v@unc.edu');
insert into customers (id, name, address, city, phone_number, e_mail) values (69, 'Sybilla Trencher', '4400 Summit Crossing', 'Semei', '595-459-2690', 'strencher1w@mozilla.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (70, 'Reuven Zanutti', '688 Luster Hill', 'Nur-Sultan', '837-608-3909', 'rzanutti1x@pinterest.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (71, 'Wynn Crankshaw', '1348 Merrick Crossing', 'Semei', '586-661-6612', 'wcrankshaw1y@behance.net');
insert into customers (id, name, address, city, phone_number, e_mail) values (72, 'Christos Cearley', '04613 North Court', 'Nur-Sultan', '546-368-3355', 'ccearley1z@vistaprint.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (73, 'Adriaens Shone', '8913 Daystar Place', 'Atyrau', '841-761-8285', 'ashone20@ucsd.edu');
insert into customers (id, name, address, city, phone_number, e_mail) values (74, 'Loleta Coursor', '5 1st Alley', 'Shymkent', '350-740-6111', 'lcoursor21@woothemes.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (75, 'Andy Byne', '1 Burning Wood Court', 'Aktau', '978-672-8295', 'abyne22@tiny.cc');
insert into customers (id, name, address, city, phone_number, e_mail) values (76, 'Teresa Breydin', '21 Hazelcrest Plaza', 'Shymkent', '686-517-5127', 'tbreydin23@eepurl.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (77, 'Avram Hugenin', '43463 Barby Alley', 'Kyzylorda', '810-864-1006', 'ahugenin24@foxnews.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (78, 'Charles Faulds', '755 Heffernan Crossing', 'Aktau', '971-358-4107', 'cfaulds25@independent.co.uk');
insert into customers (id, name, address, city, phone_number, e_mail) values (79, 'Brand Cobb', '4 Forest Dale Parkway', 'Kyzylorda', '440-332-6868', 'bcobb26@harvard.edu');
insert into customers (id, name, address, city, phone_number, e_mail) values (80, 'Buiron Hallworth', '950 Lyons Road', 'Almaty', '245-827-5858', 'bhallworth27@goo.gl');
insert into customers (id, name, address, city, phone_number, e_mail) values (81, 'Francois Jailler', '265 Ridgeview Way', 'Taraz', '775-965-4121', 'fjailler28@gov.uk');
insert into customers (id, name, address, city, phone_number, e_mail) values (82, 'Jean Snasdell', '1 Arrowood Crossing', 'Shymkent', '966-390-0777', 'jsnasdell29@virginia.edu');
insert into customers (id, name, address, city, phone_number, e_mail) values (83, 'Taddeo Mussared', '1937 Hoffman Street', 'Almaty', '321-197-4006', 'tmussared2a@xrea.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (84, 'Vicky Gannicott', '49529 Pankratz Point', 'Atyrau', '326-189-8470', 'vgannicott2b@mit.edu');
insert into customers (id, name, address, city, phone_number, e_mail) values (85, 'Mair Corrin', '6229 Bunting Park', 'Nur-Sultan', '409-426-4508', 'mcorrin2c@shareasale.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (86, 'Fran Mairs', '41 Macpherson Trail', 'Aktau', '834-303-0259', 'fmairs2d@macromedia.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (87, 'Blythe Siaskowski', '544 Prairieview Alley', 'Nur-Sultan', '689-185-4711', 'bsiaskowski2e@storify.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (88, 'Jedd Burborough', '342 Columbus Court', 'Pavlodar', '235-243-4733', 'jburborough2f@washingtonpost.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (89, 'Karole Dufoure', '93368 Mockingbird Place', 'Kyzylorda', '324-365-2626', 'kdufoure2g@stumbleupon.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (90, 'York Swynfen', '5 Messerschmidt Way', 'Kokshetau', '635-894-0604', 'yswynfen2h@ucla.edu');
insert into customers (id, name, address, city, phone_number, e_mail) values (91, 'Vanni Enders', '69652 Milwaukee Pass', 'Taraz', '228-596-5415', 'venders2i@dedecms.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (92, 'Roz Orwin', '0686 Messerschmidt Alley', 'Kokshetau', '634-990-0459', 'rorwin2j@mozilla.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (93, 'Fletch Stirtle', '26305 Rieder Center', 'Kokshetau', '951-129-5624', 'fstirtle2k@devhub.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (94, 'Fara Sannes', '95 Main Parkway', 'Pavlodar', '327-985-4513', 'fsannes2l@apple.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (95, 'Betta O''Shevlan', '77 Sugar Terrace', 'Kyzylorda', '288-643-1844', 'boshevlan2m@cmu.edu');
insert into customers (id, name, address, city, phone_number, e_mail) values (96, 'Kasper Kyberd', '77370 Maple Wood Lane', 'Atyrau', '226-921-0849', 'kkyberd2n@skyrock.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (97, 'Christabel Plues', '00833 Fairfield Circle', 'Aktobe', '256-485-3212', 'cplues2o@linkedin.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (98, 'Jerry Perl', '7044 Nova Circle', 'Pavlodar', '850-966-1376', 'jperl2p@comsenz.com');
insert into customers (id, name, address, city, phone_number, e_mail) values (99, 'Lezley Caveau', '0 Dawn Lane', 'Atyrau', '728-219-2709', 'lcaveau2q@jugem.jp');
insert into customers (id, name, address, city, phone_number, e_mail) values (100, 'Brandea Lougheed', '527 Manitowish Way', 'Aktau', '417-700-4408', 'blougheed2r@slashdot.org');
